uploads = []
outputs = []

[[generated]]
id = "fgwv8IFvCKLfgafslDtHz"
uri = "file://artifacts/moi/public/apple-logo.png"
type = "image"
title = "Apple logo for payment button"

[[generated]]
id = "cRVR1lxkbTDeohsE36dSo"
uri = "file://artifacts/moi/public/favicon-48x48.png"
type = "image"
title = "Big thick italic M favicon"

[[generated]]
id = "Vy_Ea41AZ3_UqJ4L63Cvx"
uri = "file://artifacts/moi/public/favicon-180x180.png"
type = "image"
title = "Big thick italic M touch icon"
