import { Router, type IRouter } from "express";
import healthRouter from "./health";
import contactRouter from "./contact";
import newsletterRouter from "./newsletter";
import ambassadorRouter from "./ambassador";
import restockRouter from "./restock";
import ordersRouter from "./orders";
import webhooksRouter from "./webhooks";
import paymobWebhookRouter from "./paymobWebhook";
import paymobInitRouter from "./paymobInit";
import paymobReturnRouter from "./paymobReturn";
import instapayProofRouter from "./instapayProof";
import adminRouter from "./admin";
import customerAuthRouter from "./customerAuth";
import whatsappRouter from "./whatsapp";
import bostaRouter from "./bosta";
import analyticsProxyRouter from "./analyticsProxy";
import analyticsRouter from "./analytics";
import checkoutsRouter from "./checkouts";
import abandonedCartsRouter from "./abandonedCarts";
import metaCapiRouter from "./metaCapi";

const router: IRouter = Router();

router.use(healthRouter);
router.use(contactRouter);
router.use(newsletterRouter);
router.use(ambassadorRouter);
router.use(restockRouter);
router.use(ordersRouter);
router.use(paymobInitRouter);
router.use(paymobReturnRouter);
router.use(instapayProofRouter);
router.use(adminRouter);
router.use(customerAuthRouter);
router.use(webhooksRouter);
router.use(paymobWebhookRouter);
router.use(whatsappRouter);
router.use(bostaRouter);
router.use(analyticsProxyRouter);
router.use(analyticsRouter);
router.use(checkoutsRouter);
router.use(abandonedCartsRouter);
router.use(metaCapiRouter);

export default router;
