import { Router, type IRouter } from "express";
import healthRouter from "./health";
import contactRouter from "./contact";
import newsletterRouter from "./newsletter";
import ambassadorRouter from "./ambassador";
import restockRouter from "./restock";
import ordersRouter from "./orders";
import webhooksRouter from "./webhooks";
import instapayProofRouter from "./instapayProof";
import adminRouter from "./admin";
import customerAuthRouter from "./customerAuth";
import whatsappRouter from "./whatsapp";
import bostaRouter from "./bosta";
import analyticsProxyRouter from "./analyticsProxy";
import analyticsRouter from "./analytics";
import checkoutsRouter from "./checkouts";
import abandonedCartsRouter from "./abandonedCarts";
import metaCapiRouter from "./metaCapi";
import anthropicRouter from "./anthropic/index";
import paymobRouter from "./paymob";
import checkoutRoute from "./checkout.route";
import paymobWebhookRoute from "./paymobWebhook.route";

const router: IRouter = Router();

router.use(healthRouter);
router.use(contactRouter);
router.use(newsletterRouter);
router.use(ambassadorRouter);
router.use(restockRouter);
router.use(ordersRouter);
router.use(instapayProofRouter);
router.use(adminRouter);
router.use(customerAuthRouter);
router.use(webhooksRouter);
router.use(whatsappRouter);
router.use(bostaRouter);
router.use(analyticsProxyRouter);
router.use(analyticsRouter);
router.use(checkoutsRouter);
router.use(abandonedCartsRouter);
router.use(metaCapiRouter);
router.use(anthropicRouter);
router.use(paymobRouter);
router.use(checkoutRoute);
router.use(paymobWebhookRoute);

export default router;
