// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/product-page/AppleStyle.tsx": () => import("../components/mockups/product-page/AppleStyle.tsx")
};
